# Generated by Django 3.2.3 on 2021-07-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('addess', models.TextField(max_length=100)),
                ('zip_code', models.IntegerField()),
            ],
        ),
    ]
